### ISSUE TITLE
Is this the gem's official repository now?

### ISSUE THREAD

**Issue by yb66** [clbustos/svg-graph#4]
The link on the home page is dead.

http://www.germane-software.com/repositories/public/SVG

Regards,
Iain

**Comment by clbustos** [comment]
No, it is not. But this github support the svg-graph gem on rubygems. So, is the de facto repository.
I didn't receive any complain from Germane Software, anyway.

**Comment by yb66** [comment]
Ok, thanks for clearing that up, much appreciated.
